In [196]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [197]:
import warnings
warnings.filterwarnings("ignore")

In [198]:
df=pd.read_csv("C:\AIML\Projects\india_housing_prices.csv")
df.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [199]:
df.drop('ID',axis=1,inplace=True)

In [200]:
df.isnull().sum()

State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [201]:
df['Locality']=df['Locality'].str.replace("Locality_","",regex=False)
df.head()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,Tamil Nadu,Chennai,84,Apartment,1,4740,489.76,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,Maharashtra,Pune,490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,Punjab,Ludhiana,167,Apartment,2,3642,183.79,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,Rajasthan,Jodhpur,393,Independent House,2,2741,300.29,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,Rajasthan,Jaipur,466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [202]:
df['Price_in_Lakhs']=df['Price_in_Lakhs']*100000
df.head()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,Tamil Nadu,Chennai,84,Apartment,1,4740,48976000.0,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,Maharashtra,Pune,490,Independent House,3,2364,19552000.0,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,Punjab,Ludhiana,167,Apartment,2,3642,18379000.0,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,Rajasthan,Jodhpur,393,Independent House,2,2741,30029000.0,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,Rajasthan,Jaipur,466,Villa,4,4823,18290000.0,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [203]:
df['Price_per_SqFt']=df['Price_per_SqFt']*100000
df.head()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,Tamil Nadu,Chennai,84,Apartment,1,4740,48976000.0,10000.0,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,Maharashtra,Pune,490,Independent House,3,2364,19552000.0,8000.0,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,Punjab,Ludhiana,167,Apartment,2,3642,18379000.0,5000.0,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,Rajasthan,Jodhpur,393,Independent House,2,2741,30029000.0,11000.0,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,Rajasthan,Jaipur,466,Villa,4,4823,18290000.0,4000.0,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [204]:
df['Property_Type'].nunique()

3

In [205]:
df['Property_Type'].unique()

array(['Apartment', 'Independent House', 'Villa'], dtype=object)

In [206]:
df['Property_Type'].count()

np.int64(250000)

In [207]:
df['Property_Type'].isnull().sum()

np.int64(0)

In [208]:
df['Property_Type'].value_counts()

Property_Type
Villa                83744
Independent House    83300
Apartment            82956
Name: count, dtype: int64

In [209]:
df=pd.get_dummies(df,columns=['Property_Type'])
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,Floor_No,...,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status,Property_Type_Apartment,Property_Type_Independent House,Property_Type_Villa
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,Furnished,22,...,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,True,False,False
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,Unfurnished,21,...,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,False,True,False
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,Semi-furnished,19,...,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,True,False,False
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,Furnished,21,...,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,False,True,False
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,Semi-furnished,3,...,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,False,False,True

In [210]:
df[['Property_Type_Apartment','Property_Type_Independent House','Property_Type_Villa']].isnull().sum()

Property_Type_Apartment            0
Property_Type_Independent House    0
Property_Type_Villa                0
dtype: int64

In [211]:
df[['Property_Type_Apartment','Property_Type_Independent House','Property_Type_Villa']]=df[['Property_Type_Apartment','Property_Type_Independent House','Property_Type_Villa']].astype(int)
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,Floor_No,...,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status,Property_Type_Apartment,Property_Type_Independent House,Property_Type_Villa
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,Furnished,22,...,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,1,0,0
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,Unfurnished,21,...,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,0,1,0
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,Semi-furnished,19,...,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,1,0,0
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,Furnished,21,...,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,0,1,0
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,Semi-furnished,3,...,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,0,0,1

In [212]:
df=pd.get_dummies(df,columns=['Furnished_Status'])
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Amenities,Facing,Owner_Type,Availability_Status,Property_Type_Apartment,Property_Type_Independent House,Property_Type_Villa,Furnished_Status_Furnished,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,1,0,0,True,False,False
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,0,1,0,False,False,True
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,1,0,0,False,True,False
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,0,1,0,True,False,False
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,0,0,1,False,True,False

In [213]:
df[['Furnished_Status_Furnished','Furnished_Status_Semi-furnished','Furnished_Status_Unfurnished']]=df[['Furnished_Status_Furnished','Furnished_Status_Semi-furnished','Furnished_Status_Unfurnished']].astype(int)
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Amenities,Facing,Owner_Type,Availability_Status,Property_Type_Apartment,Property_Type_Independent House,Property_Type_Villa,Furnished_Status_Furnished,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,1,0,0,1,0,0
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,0,1,0,0,0,1
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,1,0,0,0,1,0
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,0,1,0,1,0,0
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,0,0,1,0,1,0

In [214]:
df['Amenities'].value_counts()

Amenities
Pool                                        10218
Clubhouse                                   10010
Garden                                      10006
Gym                                          9938
Playground                                   9934
                                            ...
Playground, Gym, Clubhouse, Garden, Pool      369
Garden, Gym, Pool, Playground                 368
Pool, Garden, Clubhouse, Playground, Gym      367
Garden, Clubhouse, Pool, Gym                  360
Clubhouse, Pool, Garden, Playground, Gym      355
Name: count, Length: 325, dtype: int64

In [215]:
data=df['Amenities'].str.get_dummies(sep=', ')
df=pd.concat([df,data],axis=1)
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Property_Type_Independent House,Property_Type_Villa,Furnished_Status_Furnished,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,0,0,1,0,0,1,1,1,1,1
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,1,0,0,0,1,1,1,1,1,1
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,0,0,0,1,0,1,0,1,1,1
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,1,0,1,0,0,1,1,1,1,1
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,0,1,0,1,0,1,1,1,1,1

In [216]:
df[['Pool','Gym','Garden','Playground','Clubhouse']].value_counts()

Pool  Gym  Garden  Playground  Clubhouse
1     1    1       1           1            49864
                   0           1            10349
      0    0       0           0            10218
      1    1       1           0            10083
0     1    1       1           1            10016
      0    0       0           1            10010
           1       0           0            10006
1     0    1       1           1             9996
0     1    0       0           0             9938
      0    0       1           0             9934
1     1    0       1           1             9918
      0    1       0           1             5099
      1    0       1           0             5082
0     0    1       1           1             5050
      1    0       1           0             5043
      0    0       1           1             5022
           1       0           1             5021
      1    1       0           0             5004
                   1           0             4998
                   0           1             4989
1     0    0       1           1             4981
0     0    1       1           0             4979
1     0    0       1           0             4967
      1    0       0           0             4966
0     1    0       0           1             4966
1     0    0       0           1             4932
0     1    0       1           1             4928
1     0    1       1           0             4919
      1    0       0           1             4918
      0    1       0           0             4906
      1    1       0           0             4898
Name: count, dtype: int64

In [217]:
df['Availability_Status'].value_counts()

Availability_Status
Under_Construction    125035
Ready_to_Move         124965
Name: count, dtype: int64

In [218]:
df=pd.get_dummies(df,columns=['Availability_Status'])
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Furnished_Status_Furnished,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool,Availability_Status_Ready_to_Move,Availability_Status_Under_Construction
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,1,0,0,1,1,1,1,1,True,False
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,0,0,1,1,1,1,1,1,False,True
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,0,1,0,1,0,1,1,1,True,False
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,1,0,0,1,1,1,1,1,True,False
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,0,1,0,1,1,1,1,1,True,False

In [219]:
df[['Availability_Status_Ready_to_Move','Availability_Status_Under_Construction']]=df[['Availability_Status_Ready_to_Move','Availability_Status_Under_Construction']].astype(int)
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Furnished_Status_Furnished,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool,Availability_Status_Ready_to_Move,Availability_Status_Under_Construction
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,1,0,0,1,1,1,1,1,1,0
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,0,0,1,1,1,1,1,1,0,1
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,0,1,0,1,0,1,1,1,1,0
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,1,0,0,1,1,1,1,1,1,0
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,0,1,0,1,1,1,1,1,1,0

In [220]:
df['Public_Transport_Accessibility'].value_counts()

Public_Transport_Accessibility
High      83705
Low       83287
Medium    83008
Name: count, dtype: int64

In [221]:
df['Public_Transport_Accessibility'].isnull().sum()

np.int64(0)

In [222]:
df['Public_Transport_Accessibility']=df['Public_Transport_Accessibility'].map({'High':1,'Medium':2,'Low':0})

In [223]:
df['Public_Transport_Accessibility']

0         1
1         0
2         0
3         1
4         0
         ..
249995    0
249996    0
249997    1
249998    0
249999    2
Name: Public_Transport_Accessibility, Length: 250000, dtype: int64

In [224]:
df=df.drop_duplicates()

In [225]:
df[['Parking_Space','Security']]=df[['Parking_Space','Security']].replace({'Yes':1,'No':0})

In [226]:
df[['Parking_Space','Security']]

        Parking_Space  Security
0                   0         0
1                   0         1
2                   1         0
3                   1         1
4                   0         1
...               ...       ...
249995              0         0
249996              0         0
249997              1         1
249998              1         1
249999              0         0

[250000 rows x 2 columns]

In [227]:
df.dtypes

State                                      object
City                                       object
Locality                                   object
BHK                                         int64
Size_in_SqFt                                int64
Price_in_Lakhs                            float64
Price_per_SqFt                            float64
Year_Built                                  int64
Floor_No                                    int64
Total_Floors                                int64
Age_of_Property                             int64
Nearby_Schools                              int64
Nearby_Hospitals                            int64
Public_Transport_Accessibility              int64
Parking_Space                               int64
Security                                    int64
Amenities                                  object
Facing                                     object
Owner_Type                                 object
Property_Type_Apartment                     int64
Property_Type_Independent House             int64
Property_Type_Villa                         int64
Furnished_Status_Furnished                  int64
Furnished_Status_Semi-furnished             int64
Furnished_Status_Unfurnished                int64
Clubhouse                                   int64
Garden                                      int64
Gym                                         int64
Playground                                  int64
Pool                                        int64
Availability_Status_Ready_to_Move           int64
Availability_Status_Under_Construction      int64
dtype: object

In [228]:
df['Amenities'].head()

0    Playground, Gym, Garden, Pool, Clubhouse
1    Playground, Clubhouse, Pool, Gym, Garden
2            Clubhouse, Pool, Playground, Gym
3    Playground, Clubhouse, Gym, Pool, Garden
4    Playground, Garden, Gym, Pool, Clubhouse
Name: Amenities, dtype: object

In [229]:
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Furnished_Status_Furnished,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool,Availability_Status_Ready_to_Move,Availability_Status_Under_Construction
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,1,0,0,1,1,1,1,1,1,0
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,0,0,1,1,1,1,1,1,0,1
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,0,1,0,1,0,1,1,1,1,0
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,1,0,0,1,1,1,1,1,1,0
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,0,1,0,1,1,1,1,1,1,0

In [230]:
df['Total_Amenities']=df[['Clubhouse','Garden','Gym','Playground','Pool']].sum(axis=1)
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Furnished_Status_Semi-furnished,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool,Availability_Status_Ready_to_Move,Availability_Status_Under_Construction,Total_Amenities
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,0,0,1,1,1,1,1,1,0,5
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,0,1,1,1,1,1,1,0,1,5
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,1,0,1,0,1,1,1,1,0,4
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,0,0,1,1,1,1,1,1,0,5
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,1,0,1,1,1,1,1,1,0,5

In [231]:
df['Amenity Density Score']=df[['Total_Amenities','Nearby_Schools','Nearby_Hospitals','Public_Transport_Accessibility']].sum(axis=1)
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool,Availability_Status_Ready_to_Move,Availability_Status_Under_Construction,Total_Amenities,Amenity Density Score
0,Tamil Nadu,Chennai,84,1,4740,48976000.0,10000.0,1990,22,1,...,0,1,1,1,1,1,1,0,5,19
1,Maharashtra,Pune,490,3,2364,19552000.0,8000.0,2008,21,20,...,1,1,1,1,1,1,0,1,5,14
2,Punjab,Ludhiana,167,2,3642,18379000.0,5000.0,1997,19,27,...,0,1,0,1,1,1,1,0,4,21
3,Rajasthan,Jodhpur,393,2,2741,30029000.0,11000.0,1991,21,26,...,0,1,1,1,1,1,1,0,5,18
4,Rajasthan,Jaipur,466,4,4823,18290000.0,4000.0,2002,3,2,...,0,1,1,1,1,1,1,0,5,18

In [232]:
df['Amenity Density Score'].max()

np.int64(27)

In [233]:
df['Amenity Density Score'].mean()

np.float64(14.997048)

In [234]:
df.dtypes

State                                      object
City                                       object
Locality                                   object
BHK                                         int64
Size_in_SqFt                                int64
Price_in_Lakhs                            float64
Price_per_SqFt                            float64
Year_Built                                  int64
Floor_No                                    int64
Total_Floors                                int64
Age_of_Property                             int64
Nearby_Schools                              int64
Nearby_Hospitals                            int64
Public_Transport_Accessibility              int64
Parking_Space                               int64
Security                                    int64
Amenities                                  object
Facing                                     object
Owner_Type                                 object
Property_Type_Apartment                     int64
Property_Type_Independent House             int64
Property_Type_Villa                         int64
Furnished_Status_Furnished                  int64
Furnished_Status_Semi-furnished             int64
Furnished_Status_Unfurnished                int64
Clubhouse                                   int64
Garden                                      int64
Gym                                         int64
Playground                                  int64
Pool                                        int64
Availability_Status_Ready_to_Move           int64
Availability_Status_Under_Construction      int64
Total_Amenities                             int64
Amenity Density Score                       int64
dtype: object

Price trends by city

In [235]:
city=df.groupby('City')['Price_in_Lakhs'].median()
print(city)

City
Ahmedabad         25556000.0
Amritsar          25171000.0
Bangalore         25836000.0
Bhopal            25823000.0
Bhubaneswar       25296000.0
Bilaspur          25135000.0
Chennai           25691500.0
Coimbatore        25568000.0
Cuttack           24820500.0
Dehradun          25703500.0
Durgapur          25151000.0
Dwarka            25074500.0
Faridabad         25543000.0
Gaya              25720000.0
Gurgaon           25438000.0
Guwahati          25166500.0
Haridwar          25140000.0
Hyderabad         25678000.0
Indore            25230000.0
Jaipur            25163000.0
Jamshedpur        25148000.0
Jodhpur           25248000.0
Kochi             25875000.0
Kolkata           25033000.0
Lucknow           25804000.0
Ludhiana          24942000.0
Mangalore         25652000.0
Mumbai            24899000.0
Mysore            25952000.0
Nagpur            25525500.0
New Delhi         24967500.0
Noida             25652000.0
Patna             24797000.0
Pune              25893000.0
Raipur            25368000.0
Ranchi            25158000.0
Silchar           25143500.0
Surat             25823000.0
Trivandrum        24906000.0
Vijayawada        25558500.0
Vishakhapatnam    25574000.0
Warangal          25321500.0
Name: Price_in_Lakhs, dtype: float64

Correlation between area and investment return

In [236]:
df[['Size_in_SqFt','Price_in_Lakhs']].corr()

                Size_in_SqFt  Price_in_Lakhs
Size_in_SqFt        1.000000       -0.002529
Price_in_Lakhs     -0.002529        1.000000

In [237]:
df.to_csv('Feature_data.csv',index=False)

In [238]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()

df['State']=lb.fit_transform(df['State'])
df['City']=lb.fit_transform(df['City'])
df['Locality']=lb.fit_transform(df['Locality'])
df['Amenities']=lb.fit_transform(df['Amenities'])
df['Facing']=lb.fit_transform(df['Facing'])
df['Owner_Type']=lb.fit_transform(df['Owner_Type'])

In [239]:
state_mapping = dict(zip(lb.classes_,
                         lb.transform(lb.classes_)))
state_mapping

{'Broker': np.int64(0), 'Builder': np.int64(1), 'Owner': np.int64(2)}

In [240]:
city_mapping=dict(zip(lb.classes_,lb.transform(lb.classes_)))
city_mapping

{'Broker': np.int64(0), 'Builder': np.int64(1), 'Owner': np.int64(2)}

In [241]:
df.head()

,State,City,Locality,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,...,Furnished_Status_Unfurnished,Clubhouse,Garden,Gym,Playground,Pool,Availability_Status_Ready_to_Move,Availability_Status_Under_Construction,Total_Amenities,Amenity Density Score
0,15,6,483,1,4740,48976000.0,10000.0,1990,22,1,...,0,1,1,1,1,1,1,0,5,19
1,11,33,434,3,2364,19552000.0,8000.0,2008,21,20,...,1,1,1,1,1,1,0,1,5,14
2,13,25,75,2,3642,18379000.0,5000.0,1997,19,27,...,0,1,0,1,1,1,1,0,4,21
3,14,21,326,2,2741,30029000.0,11000.0,1991,21,26,...,0,1,1,1,1,1,1,0,5,18
4,14,19,407,4,4823,18290000.0,4000.0,2002,3,2,...,0,1,1,1,1,1,1,0,5,18

In [242]:
df.to_csv('cleaned_data.csv',index=False)

In [243]:
df.columns

Index(['State', 'City', 'Locality', 'BHK', 'Size_in_SqFt', 'Price_in_Lakhs',
       'Price_per_SqFt', 'Year_Built', 'Floor_No', 'Total_Floors',
       'Age_of_Property', 'Nearby_Schools', 'Nearby_Hospitals',
       'Public_Transport_Accessibility', 'Parking_Space', 'Security',
       'Amenities', 'Facing', 'Owner_Type', 'Property_Type_Apartment',
       'Property_Type_Independent House', 'Property_Type_Villa',
       'Furnished_Status_Furnished', 'Furnished_Status_Semi-furnished',
       'Furnished_Status_Unfurnished', 'Clubhouse', 'Garden', 'Gym',
       'Playground', 'Pool', 'Availability_Status_Ready_to_Move',
       'Availability_Status_Under_Construction', 'Total_Amenities',
       'Amenity Density Score'],
      dtype='object')

Classification Model: Logistic Regression, Random Forest, or XGBoost Classifier etc. (at least 5)

 Target: Good_Investment


🔹Classification: Good Investment
Goal: Decide if property is worth buying.
Price vs Median: Price ≤ median → good investment


Price per Sq Ft: Cheaper than median → good


Multi-factor Score: Combine features (BHK≥3, RERA, ready-to-move) → threshold = good

In [244]:
median_ppsf=df['Price_per_SqFt'].mean()
median_amenity=df['Amenity Density Score'].mean()
df['Good_Investment']=(
    (df['Price_per_SqFt'] <= median_ppsf) &
    
    (df['BHK'] >= 3) &
    (df['Amenity Density Score'] >= median_amenity)
).astype(int)

In [245]:
print(df['Good_Investment'].isna().sum())

0

In [246]:
df['Good_Investment'].value_counts()

Good_Investment
0    193970
1     56030
Name: count, dtype: int64

In [247]:
X=df.drop([
    'Good_Investment',
    'Price_per_SqFt',
    'BHK',
    'Amenity Density Score'],axis=1)
y=df['Good_Investment']

In [248]:
df = df.dropna(subset=['Good_Investment'])

In [249]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [250]:
X_train.select_dtypes(include='object').columns

Index([], dtype='object')

In [251]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

200000
50000
200000
50000

In [252]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

Logistic Regression

In [253]:
# from sklearn.linear_model import LogisticRegression

# m1=LogisticRegression(max_iter=1000,class_weight='balanced')
# m1.fit(X_train, y_train)

# y_pred = m1.predict(X_test)

In [254]:
# from sklearn.metrics import accuracy_score, classification_report,f1_score,confusion_matrix

# print("Accuracy:", accuracy_score(y_test,y_pred))
# print("Classification report:",classification_report(y_test,y_pred))
# print("F1 Score:",f1_score(y_test,y_pred))

Random Forest

In [255]:
# from sklearn.ensemble import RandomForestClassifier

# m2=RandomForestClassifier(n_estimators=200,class_weight='balanced',random_state=42)
# m2.fit(X_train, y_train)

# y_pred = m2.predict(X_test)

In [256]:
# from sklearn.metrics import accuracy_score, classification_report,f1_score

# print("Accuracy:", accuracy_score(y_test,y_pred))
# print("Classification report:",classification_report(y_test,y_pred))
# print("F1 Score:",f1_score(y_test,y_pred))

In [257]:
# print(len(X_test))
# print(len(y_test))
# print(len(y_pred))

Gradient Boosting

In [258]:
# from sklearn.ensemble import GradientBoostingClassifier

# m3=GradientBoostingClassifier()
# m3.fit(X_train, y_train)

# y_pred = m3.predict(X_test)

In [259]:
# from sklearn.metrics import accuracy_score, classification_report,f1_score

# print("Accuracy:", accuracy_score(y_test,y_pred))
# print("Classification report:",classification_report(y_test,y_pred))
# print("F1 Score:",f1_score(y_test,y_pred))

In [260]:
# print(len(X_test))
# print(len(y_test))
# print(len(y_pred))
# print(len(X_train))
# print(len(y_train))

XGBoost

In [261]:
# from xgboost import XGBClassifier

# m4=XGBClassifier(scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]),use_label_encoder=False, eval_metric='logloss',class_weight='balanced')
# m4.fit(X_train, y_train)

# y_pred = m4.predict(X_test)

In [262]:
# from sklearn.metrics import accuracy_score, classification_report,f1_score

# print("Accuracy:", accuracy_score(y_test,y_pred))
# print("Classification report:",classification_report(y_test,y_pred))
# print("F1 Score:",f1_score(y_test,y_pred))

KNN

In [263]:
# from sklearn.neighbors import KNeighborsClassifier

# m5 = KNeighborsClassifier()
# m5.fit(X_train, y_train)

# y_pred = m5.predict(X_test)

In [264]:
# from sklearn.metrics import accuracy_score, classification_report,f1_score

# print("Accuracy:", accuracy_score(y_test,y_pred))
# print("Classification report:",classification_report(y_test,y_pred))
# print("F1 Score:",f1_score(y_test,y_pred))

Regression Model: Linear Regression, Random Forest Regressor, or XGBoost Regressor etc. (at least 5)
 Target: Future_Price_5Y


 Regression: Future Price (5 yrs)
Goal: Predict property price in 5 years.
Fixed Rate: Future = Current * (1 + r)^t (e.g., r=8%)


By Location/Type: Use different growth rates per city/property.


Feature-based: Predict growth using property features (BHK, sqft, RERA, etc.)

In [265]:
# df['growth_rate'] = (
#     0.05
#     + 0.01 * df['Public_Transport_Accessibility']
#     + 0.005 * df['Amenity Density Score']
#     - 0.01 * df['Relative_Price']
# )

In [266]:
# df['Relative_Price'] = df['Price_per_SqFt'] / df['City_Median_PPSF']

In [267]:
# df['City_Median_PPSF'] = df.groupby('City')['Price_per_SqFt'].transform('median')

In [268]:
# df['Future_Price_5Y'] = df['Price_in_Lakhs'] * (1 + df['growth_rate']) ** 5

In [269]:
# df['Future_Price_5Y'].isnull().sum()

In [270]:
# X=df.drop(['Future_Price_5Y','Good_Investment','growth_rate','Relative_Price','City_Median_PPSF'],axis=1)
# y=df['Future_Price_5Y']

In [271]:
# df['Future_Price_5Y'].value_counts()

In [272]:
# from sklearn.model_selection import train_test_split

# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [273]:
# X_train=X_train.fillna(X_train.median())
# X_test=X_test.fillna(X_test.median())
# y_train=y_train.fillna(y_train.median())
# y_test=y_test.fillna(y_test.median())

Linear Regression

In [274]:
# from sklearn.linear_model import LinearRegression

# m1=LinearRegression()
# m1.fit(X_train,y_train)

# pred1=m1.predict(X_test)

In [275]:
# from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_squared_error

# rmse=np.sqrt(mean_squared_error(y_test,pred1))
# mae=mean_absolute_error(y_test,pred1)
# r2=r2_score(y_test,pred1)
# mse=mean_squared_error(y_test,pred1)

# print("RMSE:", rmse)
# print("MAE:", mae)
# print("R2:", r2)
# print("MSE:",mse)

Decision Tree Regressor

In [276]:
# from sklearn.tree import DecisionTreeRegressor

# m2=DecisionTreeRegressor()
# m2.fit(X_train,y_train)

# pred2=m2.predict(X_test)

In [277]:
# from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_squared_error

# rmse=np.sqrt(mean_squared_error(y_test,pred2))
# mae=mean_absolute_error(y_test,pred2)
# r2=r2_score(y_test,pred2)
# mse=mean_squared_error(y_test,pred2)

# print("RMSE:", rmse)
# print("MAE:", mae)
# print("R2:", r2)
# print("MSE:",mse)

Random Forest Regressor

In [278]:
# from sklearn.ensemble import RandomForestRegressor

# m3=RandomForestRegressor(
#     n_estimators=50,   # fewer trees
#     max_depth=10,      # limit tree size
#     n_jobs=-1,         # use all CPU cores
#     random_state=42
# )
# m3.fit(X_train,y_train)

# pred3=m3.predict(X_test)

In [279]:
# from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_squared_error

# rmse=np.sqrt(mean_squared_error(y_test,pred3))
# mae=mean_absolute_error(y_test,pred3)
# r2=r2_score(y_test,pred3)
# mse=mean_squared_error(y_test,pred3)

# print("RMSE:", rmse)
# print("MAE:", mae)
# print("R2:", r2)
# print("MSE:",mse)

GradientBoostingRegressor

In [280]:
# from sklearn.ensemble import GradientBoostingRegressor

# m4=GradientBoostingRegressor()
# m4.fit(X_train,y_train)

# pred4=m4.predict(X_test)

In [281]:
# from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_squared_error

# rmse=np.sqrt(mean_squared_error(y_test,pred4))
# mae=mean_absolute_error(y_test,pred4)
# r2=r2_score(y_test,pred4)
# mse=mean_squared_error(y_test,pred4)

# print("RMSE:", rmse)
# print("MAE:", mae)
# print("R2:", r2)
# print("MSE:",mse)

XGBoost Regressor

In [282]:
# from xgboost import XGBRegressor

# m5=XGBRegressor()
# m5.fit(X_train,y_train)

# pred5=m5.predict(X_test)

In [283]:
# from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_squared_error

# rmse=np.sqrt(mean_squared_error(y_test,pred5))
# mae=mean_absolute_error(y_test,pred5)
# r2=r2_score(y_test,pred1)
# mse=mean_squared_error(y_test,pred5)

# print("RMSE:", rmse)
# print("MAE:", mae)
# print("R2:", r2)
# print("MSE:",mse)

In [284]:
# import matplotlib.pyplot as plt

# plt.hist(df['Future_Price_5Y'], bins=50)
# plt.title("Distribution of Future Price (5Y)")
# plt.xlabel("Future Price")
# plt.ylabel("Frequency")
# plt.show()

EDA


Impact of crime rate on good investment classification

In [285]:
# import seaborn as sns

# sns.countplot(x='Security',hue='Good_Investment',data=df)
# plt.title("Impact of Security (Crime Proxy) on Investment")
# plt.show()

Relationship between infrastructure score and resale value

In [286]:
# df['Investment_Score']=(df['Public_Transport_Accessibility']+df['Nearby_Schools']+df['Nearby_Hospitals']+df['Total_Amenities'])

In [287]:
# sns.scatterplot(x='Investment_Score',y='Future_Price_5Y',data=df)
# plt.title("Infrastructure Impact on Resale Value")
# plt.show()